### ISSUE TITLE
Rhino Tank Drive

### ISSUE THREAD

**Issue by timtim17** [FRC-1294/frc2016#5]
## Todo
- [X] `RobotDrive` with 4 CIM motors
- [X] Figure out how to feed 2 encoders into 4 closed-loop Talons
  - Follower Mode
  - [X] Find examples on GitHub
- [x] Closed loop mode
  - [x] Switch between modes per command
    - [x] Add `setToVbat()` to `DriveSystem.java`
      - When you first enable the robot, it's a normal tank drive on Vbat mode (-1 to 1). However, as soon as you start `DriveStraight.java`, it calls `setToEncoders()`, and it switches over to closed-loop speed. However, after that command is over, Vbat mode doesn't get reenabled - instead, it becomes a closed-loop speed tank drive.
  - [x] Change `RobotDrive` max & min - see CiDemo
  - **Encoders on 1 & 4 (front left and right back)**
  - [x] Gyros
    - [X] Drive Straight
    - [X] Turn `x` degrees
    - [X] Drive in a square
    - [x] Turn to a specific heading
      - [x] PID Stuff - 70eec4d45af25a7e5dab3f0531fc6aa163c12921
    - [x] Tune PID for competition drive base
- [ ] ~~Refactor and clean up everything~~ - see #15

**Comment by JohnRudolfLewis** [comment]
It might be as simple as running one of them in closed loop, and one in follower, but I would suggest that you find other code examples out there that do this, in order to increase our confidence, prior to testing it out. Our current software-team robot has this configuration, if we hook the extra talons back up, we can test this out this week.

**Comment by timtim17** [comment]
Looks like follower mode would **mirror** the **output** of it's master `CANTalon` (according to the software manual).

This might work, but if, for example, the back motor was behind a little and needed to go faster, it wouldn't: it just mirrors its output.

**Comment by JohnRudolfLewis** [comment]
As long as both are mechanically linked, such as via a gearbox, then there is no way to be behind. We should test this out on Wed.

**Comment by timtim17** [comment]
Potential Examples:
- [Milken-Computer-Science/MilkenKnights-2015-Robot-Code](https://github.com/Milken-Computer-Science/MilkenKnights-2015-Robot-Code/blob/8f08d77f8e90e08f4a9d9d412602d8d7da23737c/src/com/milkenknights/frc2015/subsystems/DriveSubsystem.java#L56)

``` java
CANTalon leftTalonA = new CANTalon(Constants.CAN.DRIVE_LEFT_A_TALON);
CANTalon leftTalonB = new CANTalon(Constants.CAN.DRIVE_LEFT_B_TALON);

CANTalon rightTalonA = new CANTalon(Constants.CAN.DRIVE_RIGHT_A_TALON);
CANTalon rightTalonB = new CANTalon(Constants.CAN.DRIVE_RIGHT_B_TALON);

drive = new RobotDrive(leftTalonA, rightTalonA);

encLeft = new Encoder(Constants.DIO.DRIVE_LEFT_ENCODER_A,
        Constants.DIO.DRIVE_LEFT_ENCODER_B);
// commented out encRight definition

// ...

leftTalonB.changeControlMode(ControlMode.Follower);
rightTalonB.changeControlMode(ControlMode.Follower);

leftTalonB.set(leftTalonA.getDeviceID());
rightTalonB.set(rightTalonA.getDeviceID());

encLeft.setDistancePerPulse(-Constants.DRIVE.INCHES_PER_PULSE);
```
- [m3rcuriel/still-polishing](https://github.com/m3rcuriel/still-polishing/blob/a67833955b4edf4d2e3d45ac93cb604960432419/src/com/mvrt/frc2015/subsystems/DriveBase.java#L35)

``` java
leftDriveBaseFront = new CANTalon(Constants.kLeftDriveFront);
leftDriveBaseRear = new CANTalon(Constants.kLeftDriveRear);

rightDriveBaseFront = new CANTalon(Constants.kRightDriveFront);
rightDriveBaseRear = new CANTalon(Constants.kRightDriveRear);

leftDriveBaseRear.changeControlMode(ControlMode.Follower);
leftDriveBaseRear.set(leftDriveBaseFront.getDeviceID());

rightDriveBaseRear.changeControlMode(ControlMode.Follower);
rightDriveBaseRear.set(rightDriveBaseFront.getDeviceID());
```

**Comment by timtim17** [comment]
I think something like this would work:

``` java
CANTalon leftFront = new CANTalon(1);
CANTalon rightFront = new CANTalon(2);
CANTalon leftRear = new CANTalon(3);
CANTalon rightRear = new CANTalon(4);

RobotDrive rd = new RobotDrive(leftFront, rightFront);

leftRear.changeControlMode(CANTalon.TalonControlMode.Follower);
rightRear.changeControlMode(CANTalon.TalonControlMode.Follower);

leftRear.set(1);
rightRear.set(2);

// ...

rd.tankDrive(1, 1);
```

It would just need to be implemented fully by someone into the robot code (i.e. `DriveSubsystem` class, `RobotMap` constants, etc.). The reason why I've set the `RobotDrive` to a two motor drive is because I beieve `RobotDrive` calls `set()` on the CANTalons. Since `set()` in follower mode sets the ID of the talon to follow, it would try to follow the CANTalon with the ID between -1 and 1 - we should probably note this in an implementation comment.

**Comment by Shalmezad** [comment]
From FRC Team 2619, wanted to say a quick thank you. We were looking for some example code to verify that the documentation for TalonControlMode.Follow was correct, and google led us here. :)
