### ISSUE TITLE
Auto modes

### ISSUE THREAD

**Issue by timtim17** [FRC-1294/frc2016#8]
- [ ] Differing modes for each situation
  - [ ] Go through low bar, score a goal, and drive open door depending on position
- [ ] :question: Modes to do other things? _(i.e. do nothing, drive to defense, breach defense, ...)_ :question:

**Comment by timtim17** [comment]
See the `AutonomousModes` branch.

**Comment by timtim17** [comment]
- [X] Simple auton (just drive forward)
- [X] Aim at high goal
- [ ] Shoot at high goal
- [ ] Score low goal
  - [ ] Figure out paths to drive to aim properly
  - :question: be able to drive to either goal depending on alliance partners' auton :question:

**Comment by timtim17** [comment]
## Todo
- [ ] Low goal auto
  - [ ] pos 1
  - [ ] pos 2
  - [ ] pos 5
- [X] Defeat defense
  - Drive forward and through the defense
- [X] Reach defense
- [ ] Do nothing autonomous

``` java
protected boolean isFinished() {
  return true;
}
```
